### ISSUE TITLE
Crash on starting new world

### ISSUE THREAD

**Issue by pike713** [Mitchellbrine/DiseaseCraft-2.0#7] opened 2015-09-06 21:57 UTC
---- Minecraft Crash Report ----
// You're mean.

Time: 9/6/15 2:40 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@8589b3
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 98206624 bytes (93 MB) / 1330642944 bytes (1269 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 Optifine OptiFine_1.7.10_HD_U_C1 129 mods loaded, 129 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](modpack.jar) 
    UCHIJAAAA   Forge{10.13.4.1492} [Minecraft Forge](modpack.jar) 
    UCHIJAAAA   modJ_StarMinerCore{0.9.7} [StarMinerCore](minecraft.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   DCModLoader{1.0} [DCModuleLoader](minecraft.jar) 
    UCHIJAAAA   gasesCore{1.6.2} [Glenn's Gases Core](minecraft.jar) 
    UCHIJAAAA   gasesFrameworkCore{1.1.2} [Gases Framework Core](minecraft.jar) 
    UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   Trapcraft{v2.2.1a} [Trapcraft]([1.7.10] Trapcraft - v2.3.0a.zip) 
    UCHIJAAAA   gender{1.0.1} [Gender]([1.7.10]Gender-1.0.2.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   IC2{2.2.765-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.765-experimental.jar) 
    UCHIJAAAA   advancedgenetics{1.5.9} [Advanced Genetics](advancedgenetics-1.7.10-1.5.9.jar) 
    UCHIJAAAA   adventuremod{0.5} [Infinite Adventure Mod](AdventureMod-1.7.10-v0.5.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   modJ_StarMiner{0.9.7} [Starminer Mod](Anti-Gravity-Mod-1.7.10.jar) 
    UCHIJAAAA   AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHIJAAAA   BiblioCraft{1.10.5} [BiblioCraft](BiblioCraft[v1.10.5][MC1.7.10].jar) 
    UCHIJAAAA   Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   chisel{2.4.1.40} [Chisel 2](Chisel2-2.4.1.40.jar) 
    UCHIJAAAA   ctmlib{1.0.1.5} [CTMLib](Chisel2-2.4.1.40.jar) 
    UCHIJAAAA   ComputerCraft{1.73} [ComputerCraft](ComputerCraft1.73.jar) 
    UCHIJAAAA   BuildMod{v1.0} [Build Mod](CoroUtil-1.1.1.jar) 
    UCHIJAAAA   CoroAI{v1.0} [CoroAI](CoroUtil-1.1.1.jar) 
    UCHIJAAAA   ExtendedRenderer{v1.0} [Extended Renderer](CoroUtil-1.1.1.jar) 
    UCHIJAAAA   ConfigMod{v1.0} [Extended Mod Config](CoroUtil-1.1.1.jar) 
    UCHIJAAAA   DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) 
    UCHIJAAAA   DiseaseCraft{2.0} [DiseaseCraft](DiseaseCraft-1.7.10-2.1.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2 %281%29.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.6a.build969} [Tinkers' Construct](TConstruct-1.7.10-1.8.6a.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.9} [Extra Utilities](extrautilities-1.2.9.jar) 
    UCHIJAAAA   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJAAAA   FloodLights{0.6.1-74} [Flood Lights](FloodLights-1.7.10-0.6.1-74.jar) 
    UCHIJAAAA   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.357.jar) 
    UCHIJAAAA   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.357.jar) 
    UCHIJAAAA   gasesFramework{1.1.2} [Gases Framework](gasesFramework-1.7.10-1.1.2.jar) 
    UCHIJAAAA   gases{1.6.2} [Glenn's Gases](gases-1.7.10-1.6.2.jar) 
    UCHIJAAAA   gasesFrameworkWAILA{1.0.0} [Gases Framework WAILA plugin](gasesFrameworkWAILA-1.0.0.jar) 
    UCHIJAAAA   HardcoreDarkness{1.6} [Hardcore Darkness](HardcoreDarkness-MC1.7.10-1.6.jar) 
    UCHIJAAAA   HardcoreEnderExpansion{1.8.2} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.2.jar) 
    UCHIJAAAA   hidenames{1.1.7} [Hide Names](Hide Names-1.7.10-1.1.8.jar) 
    UCHIJAAAA   HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode](HQM-The Journey %284.2.4%29.jar) 
    UCHIJAAAA   iChunUtil{4.1.3} [iChunUtil](iChun-Util-Mod-1.7.10.jar) 
    UCHIJAAAA   InfernalMobs{1.6.0} [Infernal Mobs](InfernalMobs-1.7.10.jar) 
    UCHIJAAAA   IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHIJAAAA   journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCHIJAAAA   kwastibustmonsters{1.0.9} [Kwasti Bust Monsters](KwastiBustMonsters-1.7.10-1.0.9.jar) 
    UCHIJAAAA   RadixCore{2.0.2} [RadixCore](RadixCore-2.0.2-1.7.10-universal.jar) 
    UCHIJAAAA   MCA{1.7.10-5.0.7.2} [Minecraft Comes Alive](MCA-1.7.10-5.0.7.2-universal.jar) 
    UCHIJAAAA   Mekanism{8.1.7} [Mekanism](Mekanism-1.7.10-8.1.7.252.jar) 
    UCHIJAAAA   MekanismGenerators{8.1.7} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.7.252.jar) 
    UCHIJAAAA   MekanismTools{8.1.7} [MekanismTools](MekanismTools-1.7.10-8.1.7.252.jar) 
    UCHIJAAAA   meteors{2.14.3} [Falling Meteors](meteors-1.7.10-2.14.3.jar) 
    UCHIJAAAA   minechem{5.0.5.108} [Minechem](Minechem-5-Mod-1.7.10.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.1.0.31-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre8.92} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MoarFood{V5.9.2} [MoarFood](MoarFood-5.9.2.jar) 
    UCHIJAAAA   MorePlanet{1.2.9} [More Planets](More-Planets-1.7.10-1.2.9.jar) 
    UCHIJAAAA   me{1.3.2.1} [More Enchantments](MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UCHIJAAAA   AencEx{0.0.1} [AencEx](MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UCHIJAAAA   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UCHIJAAAA   MutantCreatures{1.4.9} [Mutant Creatures](MutantCreatures-1.7.10-1.4.9.jar) 
    UCHIJAAAA   NaturalAbsorption{1.2.1} [Natural Absorption](NaturalAbsorption-1.7.10-1.2.1.jar) 
    UCHIJAAAA   NEIAddons{1.12.11.36} [NEI Addons](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   openmodularturrets{2.1.3-163} [Open Modular Turrets](OpenModularTurrets-1.7.10-2.1.3-163.jar) 
    UCHIJAAAA   PneumaticCraft{1.9.15-104} [PneumaticCraft](PneumaticCraft-1.7.10-1.9.15-104-universal.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
    UCHIJAAAA   ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
    UCHIJAAAA   ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
    UCHIJAAAA   ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
    UCHIJAAAA   RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCHIJAAAA   secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.413.jar) 
    UCHIJAAAA   punt{1.7.10-10.13.0-16.1} [Punt](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   whitehall{1.7.10-10.13.0-16.1} [Whitehall](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   hoy{1.7.10-10.13.0-16.1} [Hoy](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   smallboats{1.7.10-10.13.0-16.1} [SmallBoats (base)](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   SolarExpansion{1.6a} [Solar Expansion](SolarExpansion-Basic-1.6a.jar) 
    UCHIJAAAA   SophisticatedWolves{3.2.0} [SophisticatedWolves](Sophisticated Wolves 3.2.0.jar) 
    UCHIJAAAA   SpecialMobs{3.1.1} [Special Mobs](SpecialMobs-1.7.10-3.1.1.jar) 
    UCHIJAAAA   SpiceOfLife{1.2.4} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.4.jar) 
    UCHIJAAAA   Sync{4.0.0} [Sync](Sync-Mod-1.7.10.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   thirstmod{1.8.14} [Thirst Mod](thirstmod-1.8.14.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJAAAA   ZAMod{v1.9.5} [Zombie Awareness](ZombieAwareness-1.9.6.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeRelocation{0.0.1.3} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
    UCHIJAAAA   MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
    UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    CoFHCore: -[1.7.10]3.0.3-303
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    TConstruct Environment: Environment healthy.
    RedstoneArsenal: -[1.7.10]1.1.1-89
    ThermalDynamics: -[1.7.10]1.1.0-161
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [GCEntityPlayerMP['pike713'/318, l='New World', x=-195.50, y=80.00, z=261.50]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Mitchellbrine** [comment] 2015-09-06 22:01
Try removing my mod. If doesn't crash, then please reply. From what I can see in this crash, my mod isn't really erroring. Might be me, but I can't tell from the error.

**Comment by pike713** [comment] 2015-09-07 01:23
This modpack has been stable for a month or so now. This began occurring after an update in which the only change was the addition of diseasecraft 2, but, just to make sure, I removed diseasecraft and was able to launch worlds just fine

**Comment by Mitchellbrine** [comment] 2015-09-07 01:34
Is this every time the world loads or just the first time?

**Comment by pike713** [comment] 2015-09-07 01:36
every time

**Comment by Mitchellbrine** [comment] 2015-09-07 02:42
What's the version (a.k.a. the file name)?

**Comment by pike713** [comment] 2015-09-07 06:51
1.7.10-2.1

**Comment by Mitchellbrine** [comment] 2015-09-07 18:38
1. Which modules are enabled/disabled?
2. Does this happen without optifine?

**Comment by pike713** [comment] 2015-09-07 19:10
1. I haven't edited the config in any way.
2. Yes, it still crashes while loading a world without Optifine.

**Comment by Mitchellbrine** [comment] 2015-09-07 19:11
Okay, try redownloading the mod and see if the issue persists. I'm not able to reproduce the issue.

**Comment by Mitchellbrine** [comment] 2015-09-07 19:12
If so, I'll take a look into my proxy, since the proxy packet is being called

**Comment by pike713** [comment] 2015-09-07 19:19
still crashing

**Comment by Mitchellbrine** [comment] 2015-09-07 19:28
Alright, can confirm in the version. Seems to me to be an issue that arrived earlier in the log, which interests me.

**Comment by Mitchellbrine** [comment] 2015-09-07 19:35
Alright, it seems to be an issue regarding the latest versions of Forge (doesn't crash in 1481). Something in the past 11 versions of Forge has caused it to happen.

**Comment by Mitchellbrine** [comment] 2015-09-07 19:38
Alright, this is a crash with the newest version of Forge only (tested in 1490 without crashing).

**Comment by Mitchellbrine** [comment] 2015-09-07 21:40
Okay, so the problem occurred earlier in the log when it threw an IllegalArgumentException because of an nbt string being empty. I have the full log on me. If you can reproduce the bug and give me that error, I can look into it from there.

**Comment by pike713** [comment] 2015-09-07 22:28
Ok, this is odd: I added Diseasecraft back into the modpack (which hasn't yet received any other changes) and now it seems to be working just fine. I was able to load existing worlds and create new ones, with all of the items form diseasecraft present and in working order.

**Comment by Mitchellbrine** [comment] 2015-09-07 22:29
Yeah, in testing, it seemed that it happened once or twice and then stopped happening.

**Comment by Mitchellbrine** [comment] 2015-10-17 01:17
I believed this is fixed in #8. At least, it is now possible for the user to fix it themselves.

**Closed as completed by Mitchellbrine** 2015-10-17 01:17 UTC
Labels: bug
